### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by bollwyvl** [agoose77/markdown-it-mermaid#4]
It would be good to get a new version of this out.

## Tasks
- [x] do another pass at versions #6
- [x] bump version number #6
- [x] add CHANGELOG #6 
- [x] build/archive in CI
- [x] add `CONTRIBUTING.md` (or issue template) with release checklist for future efforts
- [x] release on npm
